// Build-time loaders for the Chrome Valley dataset (generated by
// `python -m chrome_valley.export`). Server components in a static export
// read these JSON files from disk at build time — no runtime fetches, and
// NEVER import this file from a "use client" component.

import { readFileSync } from "node:fs";
import { join } from "node:path";

import type { LeagueData, Roster, RoundDetail } from "@/types/data";

const DATA_DIR = join(process.cwd(), "public", "data");

function readJson<T>(...segments: string[]): T {
  const path = join(DATA_DIR, ...segments);
  return JSON.parse(readFileSync(path, "utf-8")) as T;
}

let leagueCache: LeagueData | null = null;
let rosterCache: Roster | null = null;

export function getLeague(): LeagueData {
  if (!leagueCache) leagueCache = readJson<LeagueData>("chrome-valley.json");
  return leagueCache;
}

export function getRoster(): Roster {
  if (!rosterCache) rosterCache = readJson<Roster>("roster.json");
  return rosterCache;
}

export function getRound(round: number): RoundDetail {
  return readJson<RoundDetail>("rounds", `round_${String(round).padStart(2, "0")}.json`);
}

export function getAllRounds(): RoundDetail[] {
  const { rounds } = getLeague().season;
  return Array.from({ length: rounds }, (_, i) => getRound(i + 1));
}
