"""End-to-end smoke test: CSV import → value export → JSON sanity.

Replays the real workflow the user runs at the CLI without going through
``subprocess`` (the sandbox is flaky on python-subprocess invocations).
"""
from __future__ import annotations

import json
import shutil
from pathlib import Path

import pytest


SAMPLE_CSV = """driver,odds
Lando Norris,3.5
Oscar Piastri,4.0
Max Verstappen,5.5
George Russell,7.0
Charles Leclerc,9.0
Kimi Antonelli,11.0
Lewis Hamilton,13.0
Isack Hadjar,21.0
Fernando Alonso,34.0
Carlos Sainz Jr.,41.0
Alexander Albon,51.0
Lance Stroll,67.0
Oliver Bearman,81.0
Pierre Gasly,81.0
Franco Colapinto,101.0
Liam Lawson,151.0
Esteban Ocon,151.0
Gabriel Bortoleto,201.0
Arvid Lindblad,301.0
Nico Hülkenberg,401.0
Sergio Pérez,501.0
Valtteri Bottas,501.0
"""


def test_csv_to_value_round_trip(tmp_path, monkeypatch):
    """Full pipeline: CSV → odds_cache → export_value_data → value JSON.

    Pinned to round 6 because `website/public/data/probabilities/round_06.json`
    has been generated by `export_probabilities.py` already and we don't want
    to regenerate probabilities inside a unit test.
    """
    import odds_import_csv
    import export_value_data

    # Sandbox both cache dirs to tmp so we don't pollute the real ones.
    monkeypatch.setattr(odds_import_csv, "CACHE_DIR", tmp_path / "odds_cache")
    monkeypatch.setattr(export_value_data, "ODDS_CACHE_DIR", tmp_path / "odds_cache")

    # Step 1: write the sample CSV.
    csv_path = tmp_path / "canadian.csv"
    csv_path.write_text(SAMPLE_CSV)

    # Step 2: import → wrapped snapshot in tmp_path/odds_cache.
    snap = odds_import_csv.import_csv(6, 2026, "oddschecker_manual", csv_path)
    assert snap.exists()
    blob = json.loads(snap.read_text())
    assert blob["source"] == "csv-import"
    assert blob["round"] == 6

    # Step 3: run the value exporter against the real probability JSON.
    #         Requires `website/public/data/probabilities/round_06.json`.
    project_root = Path(odds_import_csv.__file__).parent
    prob_path = project_root / "website" / "public" / "data" / "probabilities" / "round_06.json"
    if not prob_path.exists():
        pytest.skip("round_06 probabilities not generated yet")

    # Patch the output dir too so we don't overwrite the real website value JSON.
    monkeypatch.setattr(
        export_value_data,
        "VALUE_DIR",
        tmp_path / "value",
    )

    result = export_value_data.export_value_data(
        round_number=6,
        season=2026,
        bankroll=1000.0,
        kelly_fraction_mult=0.25,
        per_bet_cap=0.05,
        total_cap=0.30,
        output_path=tmp_path / "value" / "round_06.json",
    )

    # Step 4: assert the schema is right.
    assert result["round"] == 6
    assert result["season"] == 2026
    assert result["bookmaker"] == "oddschecker_manual"
    assert result["bankrollRef"] == 1000.0
    assert len(result["opportunities"]) > 0

    # First opportunity should have all expected fields.
    op = result["opportunities"][0]
    for key in (
        "market", "driver", "modelProbability", "marketProbability",
        "marketOdds", "edgePct", "kellyFraction", "expectedValue",
    ):
        assert key in op, f"missing {key}"

    # Per-bet cap honoured.
    assert all(o["kellyFraction"] <= 0.05 + 1e-9 for o in result["opportunities"])
    # Total Kelly exposure stays under the configured cap (0.30).
    assert result["summary"]["totalKellyExposure"] <= 0.30 + 1e-9
    # Sorted by edge desc.
    edges = [o["edgePct"] for o in result["opportunities"]]
    assert edges == sorted(edges, reverse=True)
