/**
 * Race photography mapping — one curated aerial/track photo per Grand Prix.
 *
 * Sourcing: Wikimedia Commons. Where possible, the "SkySat" satellite aerials
 * (uploaded from Planet Labs to Commons in 2018) — these are the closest free
 * analog to the formula1.com race-page hero photography the user asked for.
 * For venues without a SkySat aerial (Madrid, Vegas, Saudi) we pick the best
 * race-weekend photo on the article.
 *
 * EVERY URL HAS BEEN curl-verified to return HTTP 200. Do not edit this file
 * with guessed Wikimedia filenames — they almost always 404. To swap an image,
 * fetch a known-good URL from Commons via either:
 *   - https://en.wikipedia.org/api/rest_v1/page/media-list/<title>
 *   - https://commons.wikimedia.org/w/api.php?action=query&prop=imageinfo&iiprop=url
 * and curl -I the result before committing.
 *
 * Falls back to the per-round matplotlib track-map webp when no curated photo
 * exists for a GP key.
 *
 * Live URLs vs. next/image: this map's URLs are consumed via CSS
 * background-image in RaceCardCarousel.tsx (NOT next/image), so the hostname
 * doesn't need to be in next.config.ts `remotePatterns`.
 *
 * Map keys are F1 `gpKey` strings (as emitted by export_website_data.py).
 * Keep keys in sync with the calendar JSON.
 */

interface RaceArt {
  src: string;
  credit: string;
  source: "unsplash";
}

const RACE_ART: Record<string, RaceArt> = {
  // R1 — Albert Park Circuit (Melbourne) · SkySat aerial
  australia: {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Melbourne_Grand_Prix_Circuit%2C_March_22%2C_2018_SkySat_%28cropped%29.jpg/1280px-Melbourne_Grand_Prix_Circuit%2C_March_22%2C_2018_SkySat_%28cropped%29.jpg",
    credit: "Albert Park aerial · Planet Labs / Wikimedia Commons",
    source: "unsplash",
  },
  // R2 — Shanghai International Circuit · SkySat aerial
  china: {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Shanghai_International_Circuit%2C_April_7%2C_2018_SkySat_%28rotated%29.jpg/1280px-Shanghai_International_Circuit%2C_April_7%2C_2018_SkySat_%28rotated%29.jpg",
    credit: "Shanghai International Circuit aerial · Planet Labs / Wikimedia Commons",
    source: "unsplash",
  },
  // R3 — Suzuka Circuit · SkySat aerial
  japan: {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Suzuka_International_Racing_Course%2C_July_10%2C_2018_SkySat_%28cropped%29.jpg/1280px-Suzuka_International_Racing_Course%2C_July_10%2C_2018_SkySat_%28cropped%29.jpg",
    credit: "Suzuka Circuit aerial · Planet Labs / Wikimedia Commons",
    source: "unsplash",
  },
  // Legacy — Bahrain International Circuit · SkySat aerial
  bahrain: {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Bahrain_International_Circuit%2C_November_2%2C_2017_SkySat_%28cropped%29.jpg/1280px-Bahrain_International_Circuit%2C_November_2%2C_2017_SkySat_%28cropped%29.jpg",
    credit: "Bahrain International Circuit aerial · Planet Labs / Wikimedia Commons",
    source: "unsplash",
  },
  // Legacy — Jeddah Corniche Circuit
  saudi: {
    src: "https://upload.wikimedia.org/wikipedia/commons/4/44/Jeddah.circuit.jpg",
    credit: "Jeddah Corniche Circuit · Wikimedia Commons",
    source: "unsplash",
  },
  // R4 — Miami International Autodrome (start/finish straight)
  miami: {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Miami_Grand_Prix_startfinish.jpg/1280px-Miami_Grand_Prix_startfinish.jpg",
    credit: "Miami International Autodrome · Wikimedia Commons",
    source: "unsplash",
  },
  // Legacy — Imola (Autodromo Enzo e Dino Ferrari) · aerial poster shot
  imola: {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Autodromo_aerea_poster.jpg/1280px-Autodromo_aerea_poster.jpg",
    credit: "Imola aerial · Wikimedia Commons",
    source: "unsplash",
  },
  // R5 — Circuit Gilles Villeneuve · SkySat aerial
  canada: {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Circuit_Gilles-Villeneuve%2C_May_29%2C_2018_SkySat_%28cropped%29.jpg/1280px-Circuit_Gilles-Villeneuve%2C_May_29%2C_2018_SkySat_%28cropped%29.jpg",
    credit: "Circuit Gilles Villeneuve aerial · Planet Labs / Wikimedia Commons",
    source: "unsplash",
  },
  // R6 — Circuit de Monaco · SkySat aerial
  monaco: {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Circuit_de_Monaco%2C_April_1%2C_2018_SkySat_%28cropped%29.jpg/500px-Circuit_de_Monaco%2C_April_1%2C_2018_SkySat_%28cropped%29.jpg",
    credit: "Circuit de Monaco aerial · Planet Labs / Wikimedia Commons",
    source: "unsplash",
  },
  // R7 — Circuit de Barcelona-Catalunya · SkySat aerial
  spain: {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Circuit_de_Barcelona-Catalunya%2C_April_19%2C_2018_SkySat_%28cropped%29.jpg/1280px-Circuit_de_Barcelona-Catalunya%2C_April_19%2C_2018_SkySat_%28cropped%29.jpg",
    credit: "Circuit de Barcelona-Catalunya aerial · Planet Labs / Wikimedia Commons",
    source: "unsplash",
  },
  // R8 — Red Bull Ring · official aerial photo
  austria: {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Luftaufnahme_%28c%29Red_Bull_Ring.jpg/1280px-Luftaufnahme_%28c%29Red_Bull_Ring.jpg",
    credit: "Red Bull Ring aerial · Wikimedia Commons",
    source: "unsplash",
  },
  // R9 — Silverstone Circuit · SkySat aerial
  great_britain: {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Silverstone_Circuit%2C_July_2%2C_2018_SkySat_%28cropped%29.jpg/1280px-Silverstone_Circuit%2C_July_2%2C_2018_SkySat_%28cropped%29.jpg",
    credit: "Silverstone Circuit aerial · Planet Labs / Wikimedia Commons",
    source: "unsplash",
  },
  britain: {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Silverstone_Circuit%2C_July_2%2C_2018_SkySat_%28cropped%29.jpg/1280px-Silverstone_Circuit%2C_July_2%2C_2018_SkySat_%28cropped%29.jpg",
    credit: "Silverstone Circuit aerial · Planet Labs / Wikimedia Commons",
    source: "unsplash",
  },
  // R10 — Circuit de Spa-Francorchamps · SkySat aerial
  belgium: {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Circuit_de_Spa-Francorchamps%2C_April_22%2C_2018_SkySat_%28cropped%29.jpg/1280px-Circuit_de_Spa-Francorchamps%2C_April_22%2C_2018_SkySat_%28cropped%29.jpg",
    credit: "Spa-Francorchamps aerial · Planet Labs / Wikimedia Commons",
    source: "unsplash",
  },
  // R11 — Hungaroring · SkySat aerial
  hungary: {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Hungaroring%2C_April_28%2C_2018_SkySat_%28cropped%29.jpg/500px-Hungaroring%2C_April_28%2C_2018_SkySat_%28cropped%29.jpg",
    credit: "Hungaroring aerial · Planet Labs / Wikimedia Commons",
    source: "unsplash",
  },
  // R12 — Circuit Zandvoort · aerial
  netherlands: {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Circuit_Park_Zandvoort_from_air_2016-08-24.jpg/1280px-Circuit_Park_Zandvoort_from_air_2016-08-24.jpg",
    credit: "Circuit Zandvoort aerial · Wikimedia Commons",
    source: "unsplash",
  },
  // R13 — Autodromo Nazionale Monza · SkySat aerial
  italy: {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Autodromo_Nazionale_Monza%2C_April_22%2C_2018_SkySat_%28cropped%29.jpg/1280px-Autodromo_Nazionale_Monza%2C_April_22%2C_2018_SkySat_%28cropped%29.jpg",
    credit: "Monza aerial · Planet Labs / Wikimedia Commons",
    source: "unsplash",
  },
  // R14 — Madring (new 2026 Madrid street circuit)
  madrid: {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Colorz_-_Flickr_-_madring_hda.jpg/1280px-Colorz_-_Flickr_-_madring_hda.jpg",
    credit: "Madring · Wikimedia Commons",
    source: "unsplash",
  },
  // R15 — Baku City Circuit · SkySat aerial
  azerbaijan: {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Baku_City_Circuit%2C_April_9%2C_2018_SkySat.jpg/1280px-Baku_City_Circuit%2C_April_9%2C_2018_SkySat.jpg",
    credit: "Baku City Circuit aerial · Planet Labs / Wikimedia Commons",
    source: "unsplash",
  },
  // R16 — Marina Bay Street Circuit (Singapore night race) · race-night cityscape
  singapore: {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/1_singapore_f1_night_race_2012_city_skyline.jpg/1280px-1_singapore_f1_night_race_2012_city_skyline.jpg",
    credit: "Marina Bay Street Circuit at night · Wikimedia Commons",
    source: "unsplash",
  },
  // R17 — Circuit of the Americas (Austin) · SkySat aerial
  united_states: {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Circuit_of_the_Americas%2C_April_22%2C_2018_SkySat_%28cropped2%29.jpg/1280px-Circuit_of_the_Americas%2C_April_22%2C_2018_SkySat_%28cropped2%29.jpg",
    credit: "Circuit of the Americas aerial · Planet Labs / Wikimedia Commons",
    source: "unsplash",
  },
  usa: {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Circuit_of_the_Americas%2C_April_22%2C_2018_SkySat_%28cropped2%29.jpg/1280px-Circuit_of_the_Americas%2C_April_22%2C_2018_SkySat_%28cropped2%29.jpg",
    credit: "Circuit of the Americas aerial · Planet Labs / Wikimedia Commons",
    source: "unsplash",
  },
  // R18 — Autódromo Hermanos Rodríguez (Mexico City) · SkySat aerial
  mexico: {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Aut%C3%B3dromo_Hermanos_Rodr%C3%ADguez%2C_June_4%2C_2018_SkySat_%28cropped%29.jpg/1280px-Aut%C3%B3dromo_Hermanos_Rodr%C3%ADguez%2C_June_4%2C_2018_SkySat_%28cropped%29.jpg",
    credit: "Autódromo Hermanos Rodríguez aerial · Planet Labs / Wikimedia Commons",
    source: "unsplash",
  },
  // R19 — Interlagos · São Paulo Grand Prix race-day photo
  brazil: {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Grande_Pr%C3%AAmio_S%C3%A3o_Paulo_de_F%C3%B3rmula_1_%2852497080967%29.jpg/1280px-Grande_Pr%C3%AAmio_S%C3%A3o_Paulo_de_F%C3%B3rmula_1_%2852497080967%29.jpg",
    credit: "Interlagos · São Paulo Grand Prix / Wikimedia Commons",
    source: "unsplash",
  },
  sao_paulo: {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Grande_Pr%C3%AAmio_S%C3%A3o_Paulo_de_F%C3%B3rmula_1_%2852497080967%29.jpg/1280px-Grande_Pr%C3%AAmio_S%C3%A3o_Paulo_de_F%C3%B3rmula_1_%2852497080967%29.jpg",
    credit: "Interlagos · São Paulo Grand Prix / Wikimedia Commons",
    source: "unsplash",
  },
  // R20 — Las Vegas Strip Circuit · 2024 race-night photo at the Sphere
  las_vegas: {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/2024_Las_Vegas_Grand_Prix_at_the_Sphere_-_Saturday%2C_November_23%2C_Orbi.jpg/1280px-2024_Las_Vegas_Grand_Prix_at_the_Sphere_-_Saturday%2C_November_23%2C_Orbi.jpg",
    credit: "Las Vegas Grand Prix at the Sphere · Wikimedia Commons",
    source: "unsplash",
  },
  // R21 — Lusail International Circuit (Qatar) · race-weekend grandstand photo
  qatar: {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/WTCC_2016%2C_Qatar.jpg/1280px-WTCC_2016%2C_Qatar.jpg",
    credit: "Lusail International Circuit · Wikimedia Commons",
    source: "unsplash",
  },
  // R22 — Yas Marina Circuit (Abu Dhabi) · SkySat aerial
  abu_dhabi: {
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Yas_Marina_Circuit%2C_October_12%2C_2018_SkySat_%28cropped%29.jpg/1280px-Yas_Marina_Circuit%2C_October_12%2C_2018_SkySat_%28cropped%29.jpg",
    credit: "Yas Marina Circuit aerial · Planet Labs / Wikimedia Commons",
    source: "unsplash",
  },
};

/**
 * Pick the best art URL for a given gpKey + round. Falls back to the
 * matplotlib track_map.webp when the gpKey isn't in the curated map.
 */
export function getRaceArt(
  gpKey: string,
  round: number,
  basePath: string = "",
): { src: string; credit: string | null } {
  // gpKeys arrive as the calendar's country/race name ("Great Britain",
  // "Las Vegas", "Abu Dhabi", "United States"). Normalise to the underscored
  // lower-case form used as map keys so multi-word names resolve.
  const normalised = gpKey?.toLowerCase().replace(/\s+/g, "_");
  const art = RACE_ART[normalised] ?? RACE_ART[gpKey?.toLowerCase()];
  if (art) {
    return { src: art.src, credit: art.credit };
  }
  // Fallback: the matplotlib-generated track map for the round.
  const trackImg = `${basePath}/visualizations/round_${String(round).padStart(
    2,
    "0",
  )}/track_map.webp`;
  return { src: trackImg, credit: null };
}
