import Link from "next/link";
import { ArrowRight, Trophy } from "lucide-react";

import RaceNight from "@/components/RaceNight";
import { getLeagueData } from "@/lib/data";

export default function HomePage() {
  const league = getLeagueData();
  const top6 = league.standings.slice(0, 6);

  return (
    <>
      {/* ── Hero ─────────────────────────────────────────────────────── */}
      <section
        className="relative overflow-hidden"
        style={{ background: "var(--gradient-paddock), var(--canvas)" }}
      >
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-24 pb-20">
          <p className="eyebrow mb-4" style={{ color: "var(--accent-prism-bright)" }}>
            Season One · Every result simulated
          </p>
          <h1 className="display-xl max-w-3xl">
            <span className="prism-text">Prism Cup</span> Karting
          </h1>
          <p className="body-md max-w-2xl mt-6">
            A fictional kart-racing league in the great arcade tradition:
            twelve original racers, eight impossible circuits, Seeker Orbs
            hunting the leader and boost pads down every straight. The whole
            season is generated by a seeded simulator — and the same engine
            runs live on this page.
          </p>
          <p className="caption-uppercase mt-4 max-w-2xl">
            A fan-made fictional league. All characters, items, tracks and
            results are simulated and original. Not affiliated with any video
            game company.
          </p>
          <div className="flex flex-wrap gap-4 mt-10">
            <Link href="/#race-night" className="btn-prism">
              Drop the flag
            </Link>
            <Link href="/cups" className="btn-bugatti">
              Season standings
            </Link>
          </div>
        </div>
        <div className="prism-hairline" />

        {/* Stat band */}
        <div className="border-b" style={{ borderColor: "var(--hairline)", background: "var(--surface-soft)" }}>
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 grid grid-cols-2 md:grid-cols-4">
            {[
              { label: "Season champion", value: league.champion.name },
              { label: "Races simulated", value: String(league.summary.totalRaces) },
              { label: "Cups", value: String(league.summary.totalCups) },
              { label: "Racers on the grid", value: String(league.summary.fieldSize) },
            ].map((stat, i) => (
              <div
                key={stat.label}
                className={`py-8 px-4 ${i > 0 ? "md:border-l" : ""}`}
                style={{ borderColor: "var(--hairline)" }}
              >
                <p className="caption-uppercase mb-2">{stat.label}</p>
                <p className="title-md" style={{ color: "var(--ink)" }}>
                  {stat.value}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Race Night (the centerpiece) ────────────────────────────── */}
      <RaceNight />

      {/* ── Season snapshot ─────────────────────────────────────────── */}
      <section className="section-bugatti">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
            <div>
              <p className="eyebrow mb-3">Season one</p>
              <h2 className="section-heading">The title fight</h2>
              <div className="card">
                {top6.map((row) => (
                  <div
                    key={row.racerId}
                    className="flex items-center gap-4 px-5 py-4 border-b last:border-b-0 racer-stripe"
                    style={
                      {
                        borderColor: "var(--hairline)",
                        "--racer-color": row.color,
                      } as React.CSSProperties
                    }
                  >
                    <span className={`position-badge ${row.rank <= 3 ? `p${row.rank}` : "points"}`}>
                      {row.rank}
                    </span>
                    <div className="min-w-0">
                      <p className="title-sm truncate" style={{ color: "var(--ink)" }}>
                        {row.name}
                      </p>
                      <p className="caption-uppercase">
                        {row.weightClass} · {row.wins} wins · {row.podiums} podiums
                      </p>
                    </div>
                    <span
                      className="ml-auto font-mono font-tabular text-sm"
                      style={{ color: "var(--body-strong)" }}
                    >
                      {row.points} pts
                    </span>
                  </div>
                ))}
                <Link
                  href="/cups"
                  className="nav-link-text flex items-center justify-between px-5 py-4 transition-colors hover:text-[color:var(--ink)]"
                  style={{ color: "var(--muted)" }}
                >
                  Full standings & race reports
                  <ArrowRight className="w-4 h-4" />
                </Link>
              </div>
            </div>

            <div>
              <p className="eyebrow mb-3">Four cups, sixteen races</p>
              <h2 className="section-heading">Cup winners</h2>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                {league.cupWinners.map((cw) => (
                  <div key={cw.number} className="card p-5">
                    <div className="flex items-center gap-2 mb-3">
                      <Trophy className="w-4 h-4" style={{ color: "var(--accent-podium-1)" }} />
                      <p className="caption-uppercase">{cw.cup}</p>
                    </div>
                    <p className="title-md" style={{ color: "var(--ink)" }}>
                      {cw.winner}
                    </p>
                    <p className="caption-uppercase mt-1">{cw.points} pts across 4 races</p>
                  </div>
                ))}
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mt-4">
                <Link href="/racers" className="card p-5 group">
                  <p className="title-sm mb-1 transition-colors group-hover:text-[color:var(--accent-prism-bright)]" style={{ color: "var(--ink)" }}>
                    Meet the racers →
                  </p>
                  <p className="body-sm" style={{ color: "var(--muted)" }}>
                    Twelve originals across three weight classes.
                  </p>
                </Link>
                <Link href="/tracks" className="card p-5 group">
                  <p className="title-sm mb-1 transition-colors group-hover:text-[color:var(--accent-prism-bright)]" style={{ color: "var(--ink)" }}>
                    Walk the tracks →
                  </p>
                  <p className="body-sm" style={{ color: "var(--muted)" }}>
                    Eight circuits from glass skyways to lava keeps.
                  </p>
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
