// Build-time loaders for the Prism Cup dataset (generated by
// `python -m prism_cup.export`). Server components in a static export read
// these JSON files from disk at build time — no runtime fetches. NEVER import
// this module from a "use client" component.

import { readFileSync } from "node:fs";
import { join } from "node:path";

import type { CupData, LeagueData, RosterData, TracksData } from "@/lib/types";

const DATA_DIR = join(process.cwd(), "public", "data");

function readJson<T>(...segments: string[]): T {
  const path = join(DATA_DIR, ...segments);
  return JSON.parse(readFileSync(path, "utf-8")) as T;
}

export function getLeagueData(): LeagueData {
  return readJson<LeagueData>("prism-cup.json");
}

export function getRoster(): RosterData {
  return readJson<RosterData>("roster.json");
}

export function getTracks(): TracksData {
  return readJson<TracksData>("tracks.json");
}

export function getCup(n: number): CupData {
  return readJson<CupData>("cups", `cup_${n}.json`);
}

export function getAllCups(): CupData[] {
  return [1, 2, 3, 4].map(getCup);
}
